// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MyWebApi.Model
{

    // MailList
    [Table("MailList", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public class MailList
    {
        [Column(@"MailListId", Order = 1, TypeName = "uniqueidentifier")]
        public System.Guid MailListId { get; set; } // MailListId (Primary key)

        [Column(@"MailTo", Order = 2, TypeName = "nvarchar(100)")]
        public string MailTo { get; set; } // MailTo (length: 100)

        [Column(@"MailContent", Order = 3, TypeName = "nvarchar(500)")]
        public string MailContent { get; set; } // MailContent (length: 500)

        [Column(@"SendStatus", Order = 4, TypeName = "int")]
        public int? SendStatus { get; set; } // SendStatus

        [Column(@"UpdateTime", Order = 5, TypeName = "datetime")]
        public System.DateTime? UpdateTime { get; set; } // UpdateTime
    }

    public enum MailListStatus
    {
        Default = 0,
        Sent = 1,
        ReceivedReply = 2
    }
}
// </auto-generated>
